FROM node

# Create app directory
WORKDIR /node/

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY node/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./node .

EXPOSE 8080
CMD [ "node", "server.js" ]