# Generated by Django 3.2.15 on 2022-08-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation', models.CharField(max_length=60)),
                ('Contact_Name', models.CharField(max_length=60)),
                ('Contact_Email', models.CharField(max_length=60)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('Phishing', models.BooleanField()),
                ('Vulnerability_Management', models.BooleanField()),
                ('Cyber_Awareness', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=60)),
                ('specialisation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapi.user')),
                ('role', models.CharField(max_length=30)),
            ],
            bases=('myapi.user',),
        ),
    ]
